<?php
namespace Booklet\Uploader;

/**
 *
 */
class MimeType
{
    public static function mimeToExtension($mime)
    {
        $mimes = [
            'audio/x-aiff' =>                       'aiff',
            'audio/basic' =>                        'au',
            'audio/midi' =>                         'midi',
            'audio/mpeg' =>                         'mp3',
            'audio/x-pn-realaudio' =>               'ra',
            'audio/x-wav' =>                        'wav',
            'audio/x-mpegurl' =>                    'm3u',
            'application/atom+xml' =>               'atom',
            'application/msword' =>                 'doc',
            'application/oda' =>                    'oda',
            'application/ogg' =>                    'ogg',
            'application/vnd.ms-powerpoint' =>      'ppt',
            'application/zip' =>                    'zip',
            'application/pdf' =>                    'pdf',
            'application/postscript' =>             'ps',
            'application/rss+xml' =>                'rss',
            'application/x-javascript' =>           'js',
            'application/json' =>                   'json',
            'application/xml-dtd' =>                'dtd',
            'application/xhtml+xml' =>              'xhtml',
            'application/xml' =>                    'xml',
            'application/vnd.wap.wbxml' =>          'wbxml',
            'application/rdf+xml' =>                'rdf',
            'application/vnd.mif' =>                'mif',
            'application/x-director' =>             'dcr',
            'application/x-bcpio' =>                'bcpio',
            'application/x-cpio' =>                 'cpio',
            'application/mac-compactpro' =>         'cpt',
            'application/x-csh' =>                  'csh',
            'application/srgs' =>                   'gram',
            'application/srgs+xml' =>               'grxml',
            'application/x-gtar' =>                 'gtar',
            'application/x-hdf' =>                  'hdf',
            'application/x-latex' =>                'latex',
            'application/x-troff-man' =>            'man',
            'application/mathml+xml' =>             'mathml',
            'application/x-troff-me' =>             'me',
            'application/x-shockwave-flash' =>      'swf',
            'application/x-tar' =>                  'tar',
            'application/x-tcl' =>                  'tcl',
            'application/x-tex' =>                  'tex',
            'application/x-texinfo' =>              'texinfo',
            'application/x-sh' =>                   'sh',
            'application/x-shar' =>                 'shar',
            'application/smil' =>                   'smil',
            'application/x-sv4cpio' =>              'sv4cpio',
            'application/x-sv4crc' =>               'sv4crc',
            'application/voicexml+xml' =>           'vxml',
            'application/vnd.ms-excel' =>           'xls',
            'application/xslt+xml' =>               'xslt',
            'application/vnd.mozilla.xul+xml' =>    'xul',
            'application/vnd.wap.wmlc' =>           'wmlc',
            'application/vnd.wap.wmlscriptc' =>     'wmlsc',
            'application/x-ustar' =>                'ustar',
            'application/x-cdlink' =>               'vcd',
            'application/x-wais-source' =>          'src',
            'application/vnd.rn-realmedia' =>       'rm',
            'application/x-netcdf' =>               'cdf',
            'application/x-chess-pgn' =>            'pgn',
            'application/x-stuffit' =>              'sit',
            'application/x-futuresplash' =>         'spl',
            'application/x-dvi' =>                  'dvi',
            'application/illustrator' =>            'ai',
            'chemical/x-pdb' =>                     'pdb',
            'image/bmp' =>                          'bmp',
            'image/vnd.djvu' =>                     'djvu',
            'image/gif' =>                          'gif',
            'image/x-icon' =>                       'ico',
            'image/ief' =>                          'ief',
            'image/png' =>                          'png',
            'image/jpeg' =>                         'jpg',
            'image/x-portable-bitmap' =>            'pbm',
            'image/x-portable-anymap' =>            'pnm',
            'image/x-portable-pixmap' =>            'ppm',
            'image/svg+xml' =>                      'svg',
            'image/tiff' =>                         'tiff',
            'image/x-xbitmap' =>                    'xbm',
            'image/x-portable-graymap' =>           'pgm',
            'image/cgm' =>                          'cgm',
            'image/vnd.wap.wbmp' =>                 'wbmp',
            'image/x-rgb' =>                        'rgb',
            'image/x-cmu-raster' =>                 'ras',
            'image/x-xwindowdump' =>                'xwd',
            'image/x-xpixmap' =>                    'xpm',
            'model/iges' =>                         'iges',
            'model/vrml' =>                         'vrml',
            'model/mesh' =>                         'mesh',
            'text/css' =>                           'css',
            'text/csv' =>                           'csv',
            'text/html' =>                          'html',
            'text/sgml' =>                          'sgml',
            'text/rtf' =>                           'rtf',
            'text/richtext' =>                      'rtx',
            'text/plain' =>                         'txt',
            'text/calendar' =>                      'ics',
            'text/vnd.wap.wml' =>                   'wml',
            'text/vnd.wap.wmlscript' =>             'wmls',
            'text/tab-separated-values' =>          'tsv',
            'video/x-msvideo' =>                    'avi',
            'video/mpeg' =>                         'mpeg',
            'video/x-sgi-movie' =>                  'movie',
            'video/quicktime' =>                    'qt',
            'video/vnd.mpegurl' =>                  'mxu',
        ];

        return $mimes[$mime] ?? false;
    }

    public static function extensionToMime($ext)
    {
        $extensions = [
            'ai'      => 'application/postscript',
            'aif'     => 'audio/x-aiff',
            'aifc'    => 'audio/x-aiff',
            'aiff'    => 'audio/x-aiff',
            'asc'     => 'text/plain',
            'atom'    => 'application/atom+xml',
            'atom'    => 'application/atom+xml',
            'au'      => 'audio/basic',
            'avi'     => 'video/x-msvideo',
            'bcpio'   => 'application/x-bcpio',
            'bin'     => 'application/octet-stream',
            'bmp'     => 'image/bmp',
            'cdf'     => 'application/x-netcdf',
            'cgm'     => 'image/cgm',
            'class'   => 'application/octet-stream',
            'cpio'    => 'application/x-cpio',
            'cpt'     => 'application/mac-compactpro',
            'csh'     => 'application/x-csh',
            'css'     => 'text/css',
            'csv'     => 'text/csv',
            'dcr'     => 'application/x-director',
            'dir'     => 'application/x-director',
            'djv'     => 'image/vnd.djvu',
            'djvu'    => 'image/vnd.djvu',
            'dll'     => 'application/octet-stream',
            'dmg'     => 'application/octet-stream',
            'dms'     => 'application/octet-stream',
            'doc'     => 'application/msword',
            'dtd'     => 'application/xml-dtd',
            'dvi'     => 'application/x-dvi',
            'dxr'     => 'application/x-director',
            'eps'     => 'application/postscript',
            'etx'     => 'text/x-setext',
            'exe'     => 'application/octet-stream',
            'ez'      => 'application/andrew-inset',
            'gif'     => 'image/gif',
            'gram'    => 'application/srgs',
            'grxml'   => 'application/srgs+xml',
            'gtar'    => 'application/x-gtar',
            'hdf'     => 'application/x-hdf',
            'hqx'     => 'application/mac-binhex40',
            'htm'     => 'text/html',
            'html'    => 'text/html',
            'ice'     => 'x-conference/x-cooltalk',
            'ico'     => 'image/x-icon',
            'ics'     => 'text/calendar',
            'ief'     => 'image/ief',
            'ifb'     => 'text/calendar',
            'iges'    => 'model/iges',
            'igs'     => 'model/iges',
            'jpe'     => 'image/jpeg',
            'jpeg'    => 'image/jpeg',
            'jpg'     => 'image/jpeg',
            'js'      => 'application/x-javascript',
            'json'    => 'application/json',
            'kar'     => 'audio/midi',
            'latex'   => 'application/x-latex',
            'lha'     => 'application/octet-stream',
            'lzh'     => 'application/octet-stream',
            'm3u'     => 'audio/x-mpegurl',
            'man'     => 'application/x-troff-man',
            'mathml'  => 'application/mathml+xml',
            'me'      => 'application/x-troff-me',
            'mesh'    => 'model/mesh',
            'mid'     => 'audio/midi',
            'midi'    => 'audio/midi',
            'mif'     => 'application/vnd.mif',
            'mov'     => 'video/quicktime',
            'movie'   => 'video/x-sgi-movie',
            'mp2'     => 'audio/mpeg',
            'mp3'     => 'audio/mpeg',
            'mpe'     => 'video/mpeg',
            'mpeg'    => 'video/mpeg',
            'mpg'     => 'video/mpeg',
            'mpga'    => 'audio/mpeg',
            'ms'      => 'application/x-troff-ms',
            'msh'     => 'model/mesh',
            'mxu'     => 'video/vnd.mpegurl',
            'nc'      => 'application/x-netcdf',
            'oda'     => 'application/oda',
            'ogg'     => 'application/ogg',
            'pbm'     => 'image/x-portable-bitmap',
            'pdb'     => 'chemical/x-pdb',
            'pdf'     => 'application/pdf',
            'pgm'     => 'image/x-portable-graymap',
            'pgn'     => 'application/x-chess-pgn',
            'png'     => 'image/png',
            'pnm'     => 'image/x-portable-anymap',
            'ppm'     => 'image/x-portable-pixmap',
            'ppt'     => 'application/vnd.ms-powerpoint',
            'ps'      => 'application/postscript',
            'qt'      => 'video/quicktime',
            'ra'      => 'audio/x-pn-realaudio',
            'ram'     => 'audio/x-pn-realaudio',
            'ras'     => 'image/x-cmu-raster',
            'rdf'     => 'application/rdf+xml',
            'rgb'     => 'image/x-rgb',
            'rm'      => 'application/vnd.rn-realmedia',
            'roff'    => 'application/x-troff',
            'rss'     => 'application/rss+xml',
            'rtf'     => 'text/rtf',
            'rtx'     => 'text/richtext',
            'sgm'     => 'text/sgml',
            'sgml'    => 'text/sgml',
            'sh'      => 'application/x-sh',
            'shar'    => 'application/x-shar',
            'silo'    => 'model/mesh',
            'sit'     => 'application/x-stuffit',
            'skd'     => 'application/x-koan',
            'skm'     => 'application/x-koan',
            'skp'     => 'application/x-koan',
            'skt'     => 'application/x-koan',
            'smi'     => 'application/smil',
            'smil'    => 'application/smil',
            'snd'     => 'audio/basic',
            'so'      => 'application/octet-stream',
            'spl'     => 'application/x-futuresplash',
            'src'     => 'application/x-wais-source',
            'sv4cpio' => 'application/x-sv4cpio',
            'sv4crc'  => 'application/x-sv4crc',
            'svg'     => 'image/svg+xml',
            'svgz'    => 'image/svg+xml',
            'swf'     => 'application/x-shockwave-flash',
            't'       => 'application/x-troff',
            'tar'     => 'application/x-tar',
            'tcl'     => 'application/x-tcl',
            'tex'     => 'application/x-tex',
            'texi'    => 'application/x-texinfo',
            'texinfo' => 'application/x-texinfo',
            'tif'     => 'image/tiff',
            'tiff'    => 'image/tiff',
            'tr'      => 'application/x-troff',
            'tsv'     => 'text/tab-separated-values',
            'txt'     => 'text/plain',
            'ustar'   => 'application/x-ustar',
            'vcd'     => 'application/x-cdlink',
            'vrml'    => 'model/vrml',
            'vxml'    => 'application/voicexml+xml',
            'wav'     => 'audio/x-wav',
            'wbmp'    => 'image/vnd.wap.wbmp',
            'wbxml'   => 'application/vnd.wap.wbxml',
            'wml'     => 'text/vnd.wap.wml',
            'wmlc'    => 'application/vnd.wap.wmlc',
            'wmls'    => 'text/vnd.wap.wmlscript',
            'wmlsc'   => 'application/vnd.wap.wmlscriptc',
            'wrl'     => 'model/vrml',
            'xbm'     => 'image/x-xbitmap',
            'xht'     => 'application/xhtml+xml',
            'xhtml'   => 'application/xhtml+xml',
            'xls'     => 'application/vnd.ms-excel',
            'xml'     => 'application/xml',
            'xpm'     => 'image/x-xpixmap',
            'xsl'     => 'application/xml',
            'xslt'    => 'application/xslt+xml',
            'xul'     => 'application/vnd.mozilla.xul+xml',
            'xwd'     => 'image/x-xwindowdump',
            'xyz'     => 'chemical/x-xyz',
            'zip' => 'application/zip'
        ];

        return $extensions[$ext] ?? false;
    }

    public static function isImage($mime)
    {
        return in_array($mime, [
            'image/bmp',
            'image/gif',
            'image/ief',
            'image/png',
            'image/jpeg',
            'image/svg+xml',
            'image/tiff',
            'image/cgm',
            'image/vnd.djvu',
            'image/vnd.wap.wbmp',
            'image/x-icon',
            'image/x-rgb',
            'image/x-cmu-raster',
            'image/x-portable-bitmap',
            'image/x-portable-anymap',
            'image/x-portable-pixmap',
            'image/x-portable-graymap',
            'image/x-xbitmap',
            'image/x-xwindowdump',
            'image/x-xpixmap',
        ]);
    }
}
